# version: '3.8'

services:
  backend:
    build: ./Back-end
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped

  auth:
    build: ./Back-end
    command: ["node", "auth/app.js"]
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - AUTH_PORT=5002
      - SESSION_SECRET=${SESSION_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - backend
    restart: unless-stopped

  frontend:
    build: ./Front-end
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
      - auth
    restart: unless-stopped